repos:
  - repo: local
    hooks:
      - id: lint
        name: ruff
        entry: ruff check
        language: system
        always_run: true
        pass_filenames: false
      - id: format
        name: ruff
        entry: ruff format
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        always_run: true
        pass_filenames: false
      - id: validate-courses
        name: validate courses
        entry: bash -c 'for file in courses/*.yaml; do python noobular/validate.py "$file" || exit 1; done'
        language: system
        always_run: true
        pass_filenames: false
